### ISSUE TITLE
Trying to create a UR10 model -- visual orientations are wrong

### ISSUE THREAD

**Issue by alper111** [deepmind/mujoco_menagerie#10]
Hi. I am trying to create a UR10e model by following the steps in https://github.com/deepmind/mujoco_menagerie/blob/main/universal_robots_ur5e/README.md. However, when I load the model, visuals are not in the correct orientation. Below is a screenshot of the model:

![ur10_1](https://user-images.githubusercontent.com/12106566/216815975-d432a324-db31-47b5-828e-f93cf71444fa.png)
![ur10_2](https://user-images.githubusercontent.com/12106566/216815986-65d34dcd-6b79-4114-a8d0-fa381fe7e7e9.png)

I thought maybe I have missed a step while converting from DAE to OBJ in Blender, and I realized that the rotation is not [0, 0, 0] when I imported DAE files (but [90, 0, -180]). So I have changed them to [0, 0, 0] and re-converted the files. Visuals have changed, but they are still incorrect:

![ur10_3](https://user-images.githubusercontent.com/12106566/216816118-dd4d257b-ac20-42ca-9d50-26b57f4216b5.png)
![ur10_4](https://user-images.githubusercontent.com/12106566/216816131-c8ee5d84-2ac8-479e-9af3-c2b730f09e60.png)

I think the only difference between ur5e and ur10e should be their sizes and lengths, not orientations. I uploaded my changes to a repo if you want to check it: https://github.com/alper111/ur10e_mujoco. Files that are converted with [90, 0, -180] rotation are in `assets`, and with [0, 0, 0] rotation are in `assets2`. There may be some other issues such as colors/Kp values and so on, but they are not relevant at the moment.

Blender: Version 3.4.1 (2022-12-20)
Mujoco: Version 2.3.1
System: macOS Ventura 13.1
Architecture: arm

**Comment by kevinzakka** [comment]
Hi @alper111, I assume you have DAE or STL meshes and you're converting them to OBJ? I used Blender for this process and had to make sure I was saving the meshes with Z point up. Can you double check if you're doing that?

**Comment by alper111** [comment]
Hi Kevin. Pointing them upwards Z worked. I reinitialized the https://github.com/alper111/ur10e_mujoco repo with all the new changes. I mostly followed your conventions, but I am not opening a PR because I didn't do any system identification. Feel free to copy it for future releases, though.

**Comment by kevinzakka** [comment]
@alper111 Awesome! Feel free to submit a PR, sys ID is planned for later this year anyway.
