### ISSUE TITLE
Contributing to model system identification suggestions

### ISSUE THREAD

**Issue by raghavauppuluri13** [deepmind/mujoco_menagerie#12]
Hello! Thanks for taking the initiative to consolidate a set of high-quality models for mujoco! In our research lab, we have the physical models for the panda, ur5e, and robotiq gripper. Are there any recommended experiments for system ID that we could do to contribute to improving the current quality of these models?

**Comment by yuvaltassa** [comment]
We are planning a sysID package which we will release publicly and also use for the robots that we have hardware access to. The package documentation will contain information on data collection best practices.

I will update here when the package is released or when we have updated the robot models you mentioned.

Thanks!

**Comment by peterdavidfagan** [comment]
+1 on this sysID package this would be great to have access to even if only for learning/teaching purposes.
