### ISSUE TITLE
Finger tip positions

### ISSUE THREAD

**Issue by Masoudghanei** [deepmind/mujoco_menagerie#15]
Hello, for E3M5 hand model, How can I extract the cartesian positions of finger tips?
xanchor gives me the joints positions but, I also need the fingertips positions.

**Comment by Masoudghanei** [comment]
I could handle it by adding site to the finger tips in xml file.

**Comment by kevinzakka** [comment]
@Masoudghanei Adding sites and querying their `xpos` is indeed the mujoco thing to do!

**Comment by Masoudghanei** [comment]
@kevinzakka thank you for your answer, I have another problem.
I want to save positions related to each frame but, it just saves the positions of final frame.
I use this code:

positions = []
frames = [] 
mujoco.mj_step(model, data) 
if len(frames) < data.time * framerate:
        renderer.update_scene(data)
        pixels = renderer.render().copy()
        frames.append(pixels)
        positions.append(data.site_xpos)
        

media.show_video(frames, fps=framerate)

**Comment by yuvaltassa** [comment]
data.site_xpos.copy()
