### ISSUE TITLE
Unitree models falling backwards

### ISSUE THREAD

**Issue by jlhalv92** [deepmind/mujoco_menagerie#17]
First of all, 

thanks a lot for the models!! It is a great addition to the robotics and RL community. 

I recently started using the Unitree Go1 model with the Python Mujoco viewer, but every time I render the model, the robot falls backward. 

Do you have any initial pos configuration that I can use to replicate the stable standup position shown in the demo? 

thanks a lot for your help

**Comment by kevinzakka** [comment]
Reset to this [keyframe](https://github.com/deepmind/mujoco_menagerie/blob/main/unitree_go1/go1.xml#L224).

**Comment by jlhalv92** [comment]
Hi @kevinzakka, thanks for the fast response, but I'm using exactly that keyframe. When I'm running the viewer with scene.xml, the robot still flips back.

Are you using perhaps a different scene.xml for rendering the robot? 

thanks

**Comment by kevinzakka** [comment]
Can you try loading it in the simulate viewer and resetting to that keyframe?

**Comment by kevinzakka** [comment]
@jlhalv92 Any updates on this? I'm not having issues on my end.

**Comment by jlhalv92** [comment]
Hi @kevinzakka fixed! I was not importing the key frames correctly, thanks a lot for your support
