### ISSUE TITLE
Control Input GO1

### ISSUE THREAD

**Issue by jlhalv92** [deepmind/mujoco_menagerie#18]
Dear Developers Menagerie,

Could you please tell me what is the actual control signal for the go1 model? For me is not clear if the control input is torque or angle joint angles.

 In case the control input is Q_POS (Joint angles), does it means that I can embed a PD controller in the simulator to follow the given control reference? if this is the case, can you tell me how to configure the controller for the joints? 

Thanks for your time

Best,

Jose Luis

**Comment by kevinzakka** [comment]
Hi @jlhalv92,

The actuators are defined [here](https://github.com/deepmind/mujoco_menagerie/blob/main/unitree_go1/go1.xml#L209). It's currently position controlled. You can switch to `motor`s and embed your own PD controller. I recommend you read the [Actuator section](https://mujoco.readthedocs.io/en/latest/computation.html#geactuation) of the docs to learn more.

**Comment by jlhalv92** [comment]
Dear Kevin, 

Thanks for your tip, I switched the actuators to motors and implemented the pd controller and created the environment with composer. 

However, would like to have my go1 model as part of suite. Do you have any tips of how can I embed the controller in that scenario? I was reading the documentation but I couldn't find a way of doing it

Thanks again for your help,

Best
