### ISSUE TITLE
Grading System Question

### ISSUE THREAD

**Issue by natolambert** [deepmind/mujoco_menagerie#2]
Hi team -- this seems like a great addition. I was wondering how you came up with the grading system. Do you compare sim2real on publicly accessible data? I'm interested from just a model-learning for control perspective. 

I think releasing the grading system and data would be of interest to the community 🤗! Thanks!

**Comment by yuvaltassa** [comment]
Hi Nathan,

The grading system comes from a combination of user experience with certain models for robots that we have (e.g., as you say, sim2real performance) and just eyeballing the numbers. Sometimes it is very easy to tell that values are not in the ballpark of realism. In some cases, e.g. the Cassie, a complicated mechanical structure (4-bar linkage with some bodies having small relative masses) makes the model intrinsically less stable. We are actively working with manufacturers to improve the models and our medium term plan is to release a proper sysID package (which we will use to identify the robots we own), and eventually bring all the models to A+ status.
