### ISSUE TITLE
shadow left hand metacarpal joint is wrong

### ISSUE THREAD

**Issue by lianghongzhuo** [deepmind/mujoco_menagerie#3]
The axis of metacarpal is wrong.
Should be:
```
<default class="metacarpal">
  <joint axis="0.573576 0 -0.819152" range="0 0.785398"/>
  <position ctrlrange="0 0.785398"/>
</default>
```
before:
![image](https://user-images.githubusercontent.com/16577120/191450075-10fd84be-c213-4348-b070-69707515020e.png)

after:
![image](https://user-images.githubusercontent.com/16577120/191450270-8dac75e2-4fb8-44f3-a0ec-c5f26dd87e77.png)

**Comment by kevinzakka** [comment]
Thanks for catching @lianghongzhuo, pushing a fix shortly!
