### ISSUE TITLE
Stepping simulation changes robot configuration

### ISSUE THREAD

**Issue by rpapallas** [deepmind/mujoco_menagerie#5]
**Which model is the issue affecting?** Franka Emika Panda

**What is the issue?** I load the scene in Python (using the `mujoco.MjModel.from_xml_path` function) and then change the arm configuration (set `qpos`) to some default/home position (see figure 1). Then, if I step the simulation (`mujoco.mj_step`) multiple times, without changing anything or without sending controls to actuators, the robot configuration changes to figure 2. I then try to send zero controls + qfrc to the actuators to keep the robot still, but I can't seem to actuate the arm either:

```
 for i, joint_name in enumerate(self.joint_names):
     qfrc = self.data.joint(joint_name).qfrc_bias
     self.data.actuator(f'actuator{i+1}').ctrl = qfrc + controls[i]
```

![image](https://user-images.githubusercontent.com/6514550/196465096-5e066ab2-7b03-432c-8c08-48ef5e963048.png)

![image](https://user-images.githubusercontent.com/6514550/196465133-353b5de3-bd20-48e7-b00c-63978f60fd4a.png)

The fact that the arm moves upwards seems strange, I would expect gravity to pull the robot down instead.
Is this a problem with the model or something wrong on my side? Did you try actuating the specific model?

**Comment by rpapallas** [comment]
I see; thank you for your response @kevinzakka. I didn't realize that the `<general>` actuator is a position servo!

**Comment by kevinzakka** [comment]
@rpapallas yeah I'd recommend you open the model in the simulate binary and then play with the actuators in the right pane!
