### ISSUE TITLE
How to apply the menagerie model to the dm_control?

### ISSUE THREAD

**Issue by gemcollector** [deepmind/mujoco_menagerie#8]
Hi, I am so exicited to see these new models !! Can we utilize this new models in dm_control for RL training now? Have you design different tasks with these models? Hope for your answering~ thx~!

**Comment by kevinzakka** [comment]
Hi @gemcollector, I've successfully used a few models with `dm_control` by wrapping them in a [`composer.Entity`](https://github.com/deepmind/dm_control/blob/main/dm_control/composer/entity.py) class. Take a look at how `dm_robotics` does this in their `models/` directory, for example [for their sawyer arm](https://github.com/deepmind/dm_robotics/tree/main/py/moma/models/robots/robot_arms).
